services:
  flask-app:
    build:
      context: ./
      dockerfile: Dockerfile
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask-app